<a href="https://colab.research.google.com/github/mericgn/gz-dbt-repository/blob/main/Airline_Delay_2017_Meri%C3%A7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

pd.set_option('display.max_columns', None)

df = pd.read_csv("2017.csv.zip")

df["FL_DATE"] = pd.to_datetime(df["FL_DATE"])
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
0,2017-01-01,AA,1,JFK,LAX,800,831.0,31.0,25.0,856.0,1143.0,26.0,1142,1209.0,27.0,0.0,NaN,0.0,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0,NaN
1,2017-01-01,AA,2,LAX,JFK,900,934.0,34.0,34.0,1008.0,1757.0,12.0,1727,1809.0,42.0,0.0,NaN,0.0,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0,NaN
2,2017-01-01,AA,4,LAX,JFK,1130,1221.0,51.0,20.0,1241.0,2025.0,15.0,1958,2040.0,42.0,0.0,NaN,0.0,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0,NaN
3,2017-01-01,AA,5,DFW,HNL,1135,1252.0,77.0,19.0,1311.0,1744.0,5.0,1612,1749.0,97.0,0.0,NaN,0.0,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0,NaN
4,2017-01-01,AA,6,OGG,DFW,1855,1855.0,0.0,16.0,1911.0,631.0,11.0,600,642.0,42.0,0.0,NaN,0.0,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0,NaN

In [4]:
df = df.drop(columns=['Unnamed: 27'])
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2017-01-01,AA,1,JFK,LAX,800,831.0,31.0,25.0,856.0,1143.0,26.0,1142,1209.0,27.0,0.0,NaN,0.0,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0
1,2017-01-01,AA,2,LAX,JFK,900,934.0,34.0,34.0,1008.0,1757.0,12.0,1727,1809.0,42.0,0.0,NaN,0.0,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0
2,2017-01-01,AA,4,LAX,JFK,1130,1221.0,51.0,20.0,1241.0,2025.0,15.0,1958,2040.0,42.0,0.0,NaN,0.0,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0
3,2017-01-01,AA,5,DFW,HNL,1135,1252.0,77.0,19.0,1311.0,1744.0,5.0,1612,1749.0,97.0,0.0,NaN,0.0,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0
4,2017-01-01,AA,6,OGG,DFW,1855,1855.0,0.0,16.0,1911.0,631.0,11.0,600,642.0,42.0,0.0,NaN,0.0,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0

In [5]:
delay_cols = ['CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY','DEP_DELAY','TAXI_OUT','WHEELS_OFF','CRS_ELAPSED_TIME','ACTUAL_ELAPSED_TIME','AIR_TIME','DISTANCE']
df[delay_cols] = df[delay_cols].fillna(0)
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2017-01-01,AA,1,JFK,LAX,800,831.0,31.0,25.0,856.0,1143.0,26.0,1142,1209.0,27.0,0.0,NaN,0.0,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0
1,2017-01-01,AA,2,LAX,JFK,900,934.0,34.0,34.0,1008.0,1757.0,12.0,1727,1809.0,42.0,0.0,NaN,0.0,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0
2,2017-01-01,AA,4,LAX,JFK,1130,1221.0,51.0,20.0,1241.0,2025.0,15.0,1958,2040.0,42.0,0.0,NaN,0.0,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0
3,2017-01-01,AA,5,DFW,HNL,1135,1252.0,77.0,19.0,1311.0,1744.0,5.0,1612,1749.0,97.0,0.0,NaN,0.0,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0
4,2017-01-01,AA,6,OGG,DFW,1855,1855.0,0.0,16.0,1911.0,631.0,11.0,600,642.0,42.0,0.0,NaN,0.0,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0

In [6]:
import pandas as pd
import numpy as np

def format_time_safe(val):
    if pd.isna(val):
        return np.nan

    # Convert to string and remove colons if present
    val_str_raw = str(val)
    val_str_cleaned = val_str_raw.replace(':', '').strip()

    # Try to convert to int. Use float first to handle cases like '900.0'.
    # If it cannot be converted to a number, it's an invalid time.
    try:
        val_int = int(float(val_str_cleaned))
        val_str_padded = str(val_int).zfill(4)
    except ValueError:
        return np.nan # If it cannot be converted to int, it's an invalid time

    # Now parse hours and minutes from the padded string
    if len(val_str_padded) != 4: # Ensure it's a 4 digit time
        return np.nan

    hours = int(val_str_padded[:2])
    minutes = int(val_str_padded[2:])

    # Handle '2400' as '00:00'
    if hours == 24 and minutes == 0:
        return "00:00"

    # Validate hours and minutes (allowing 24:00 to be handled above)
    if not (0 <= hours <= 23) or not (0 <= minutes <= 59):
        return np.nan

    return f"{hours:02d}:{minutes:02d}"

time_cols = ['CRS_DEP_TIME', 'DEP_TIME','WHEELS_OFF']
for col in time_cols:
    df[col] = df[col].apply(format_time_safe)

In [7]:
df

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2017-01-01,AA,1,JFK,LAX,08:00,08:31,31.0,25.0,08:56,1143.0,26.0,1142,1209.0,27.0,0.0,NaN,0.0,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0
1,2017-01-01,AA,2,LAX,JFK,09:00,09:34,34.0,34.0,10:08,1757.0,12.0,1727,1809.0,42.0,0.0,NaN,0.0,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0
2,2017-01-01,AA,4,LAX,JFK,11:30,12:21,51.0,20.0,12:41,2025.0,15.0,1958,2040.0,42.0,0.0,NaN,0.0,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0
3,2017-01-01,AA,5,DFW,HNL,11:35,12:52,77.0,19.0,13:11,1744.0,5.0,1612,1749.0,97.0,0.0,NaN,0.0,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0
4,2017-01-01,AA,6,OGG,DFW,18:55,18:55,0.0,16.0,19:11,631.0,11.0,600,642.0,42.0,0.0,NaN,0.0,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5674616,2017-12-31,UA,2421,IAH,LAS,07:50,07:44,-6.0,14.0,07:58,849.0,4.0,916,853.0,-23.0,0.0,NaN,0.0,206.0,189.0,171.0,1222.0,0.0,0.0,0.0,0.0,0.0
5674617,2017-12-31,UA,2425,RSW,ORD,16:11,16:02,-9.0,12.0,16:14,1753.0,12.0,1821,1805.0,-16.0,0.0,NaN,0.0,190.0,183.0,159.0,1120.0,0.0,0.0,0.0,0.0,0.0
5674618,2017-12-31,UA,2426,SNA,DEN,13:35,13:34,-1.0,9.0,13:43,1627.0,10.0,1649,1637.0,-12.0,0.0,NaN,0.0,134.0,123.0,104.0,846.0,0.0,0.0,0.0,0.0,0.0
5674619,2017-12-31,UA,2427,LAS,SFO,11:15,11:07,-8.0,11.0,11:18,1224.0,15.0,1254,1239.0,-15.0,0.0,NaN,0.0,99.0,92.0,66.0,414.0,0.0,0.0,0.0,0.0,0.0
5674620,2017-12-31,UA,2429,EWR,DEN,15:10,16:12,62.0,28.0,16:40,1827.0,11.0,1740,1838.0,58.0,0.0,NaN,0.0,270.0,266.0,227.0,1605.0,58.0,0.0,0.0,0.0,0.0

In [8]:
dl_sayisi = (df['OP_CARRIER'] == 'DL').sum()
print("DL Sayısı:", dl_sayisi)

DL Sayısı: 923560

In [9]:
df['OP_CARRIER'].value_counts()

OP_CARRIER
WN    1329444
DL     923560
AA     896348
OO     706527
UA     584481
EV     339541
B6     298654
AS     185068
NK     156818
F9     103027
HA      80172
VX      70981
Name: count, dtype: int64

In [10]:
a_sayisi = (df['CANCELLATION_CODE'] == 'A').sum()
b_sayisi = (df['CANCELLATION_CODE'] == 'B').sum()
c_sayisi = (df['CANCELLATION_CODE'] == 'C').sum()
d_sayisi = (df['CANCELLATION_CODE'] == 'D').sum()


print("A Kodu Sayısı:", a_sayisi)
print("B Kodu Sayısı:", b_sayisi)
print("C Kodu Sayısı:", c_sayisi)
print("D Kodu Sayısı:", d_sayisi)

A Kodu Sayısı: 18602
B Kodu Sayısı: 48459
C Kodu Sayısı: 15313
D Kodu Sayısı: 319

In [11]:
gecikme_nedenleri = [
"CARRIER_DELAY",
"WEATHER_DELAY",
"NAS_DELAY",
"SECURITY_DELAY",
"LATE_AIRCRAFT_DELAY"
]

df[gecikme_nedenleri] = df[gecikme_nedenleri].fillna(0)
df

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2017-01-01,AA,1,JFK,LAX,08:00,08:31,31.0,25.0,08:56,1143.0,26.0,1142,1209.0,27.0,0.0,NaN,0.0,402.0,398.0,347.0,2475.0,27.0,0.0,0.0,0.0,0.0
1,2017-01-01,AA,2,LAX,JFK,09:00,09:34,34.0,34.0,10:08,1757.0,12.0,1727,1809.0,42.0,0.0,NaN,0.0,327.0,335.0,289.0,2475.0,34.0,0.0,8.0,0.0,0.0
2,2017-01-01,AA,4,LAX,JFK,11:30,12:21,51.0,20.0,12:41,2025.0,15.0,1958,2040.0,42.0,0.0,NaN,0.0,328.0,319.0,284.0,2475.0,7.0,0.0,0.0,0.0,35.0
3,2017-01-01,AA,5,DFW,HNL,11:35,12:52,77.0,19.0,13:11,1744.0,5.0,1612,1749.0,97.0,0.0,NaN,0.0,517.0,537.0,513.0,3784.0,77.0,0.0,20.0,0.0,0.0
4,2017-01-01,AA,6,OGG,DFW,18:55,18:55,0.0,16.0,19:11,631.0,11.0,600,642.0,42.0,0.0,NaN,0.0,425.0,467.0,440.0,3711.0,0.0,0.0,42.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5674616,2017-12-31,UA,2421,IAH,LAS,07:50,07:44,-6.0,14.0,07:58,849.0,4.0,916,853.0,-23.0,0.0,NaN,0.0,206.0,189.0,171.0,1222.0,0.0,0.0,0.0,0.0,0.0
5674617,2017-12-31,UA,2425,RSW,ORD,16:11,16:02,-9.0,12.0,16:14,1753.0,12.0,1821,1805.0,-16.0,0.0,NaN,0.0,190.0,183.0,159.0,1120.0,0.0,0.0,0.0,0.0,0.0
5674618,2017-12-31,UA,2426,SNA,DEN,13:35,13:34,-1.0,9.0,13:43,1627.0,10.0,1649,1637.0,-12.0,0.0,NaN,0.0,134.0,123.0,104.0,846.0,0.0,0.0,0.0,0.0,0.0
5674619,2017-12-31,UA,2427,LAS,SFO,11:15,11:07,-8.0,11.0,11:18,1224.0,15.0,1254,1239.0,-15.0,0.0,NaN,0.0,99.0,92.0,66.0,414.0,0.0,0.0,0.0,0.0,0.0
5674620,2017-12-31,UA,2429,EWR,DEN,15:10,16:12,62.0,28.0,16:40,1827.0,11.0,1740,1838.0,58.0,0.0,NaN,0.0,270.0,266.0,227.0,1605.0,58.0,0.0,0.0,0.0,0.0

In [12]:
df[gecikme_nedenleri].isnull().sum()

CARRIER_DELAY          0
WEATHER_DELAY          0
NAS_DELAY              0
SECURITY_DELAY         0
LATE_AIRCRAFT_DELAY    0
dtype: int64